### ISSUE TITLE
Object.basename is deprecated.

### ISSUE THREAD

**Issue by crstauf** [vn-ki/bracket-colorizer#14]
Arguments to `path.basename` must be strings
```
Object.basename (/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:31:10)
Object.processEditor (/Users/caleb/.atom/packages/bracket-colorizer/lib/bracket-colorizer.js:92:57)
<unknown> (/Users/caleb/.atom/packages/bracket-colorizer/lib/bracket-colorizer.js:58:20)
Function.simpleDispatch (<embedded>:11:1172318)
Emitter.emit (<embedded>:11:1173759)
stoppedChangingActivePaneItemTimeout.setTimeout (<embedded>:11:425634)
```

**Comment by linjialiang** [comment]
> `nms-color-bracket` This problem has been around for so long that it seems to have gone unmaintained

![default](https://user-images.githubusercontent.com/8848263/53778655-711daf00-3f38-11e9-88fa-9d28151f5931.png)

**Comment by UziTech** [comment]
[nms-color-bracket](https://github.com/nmscholl/nms-color-bracket) is a different package.

This issue has a pr(#15)
