### ISSUE TITLE
The color of the light topic brackets is too ugly

### ISSUE THREAD

**Issue by linjialiang** [vn-ki/bracket-colorizer#16]
> The color of the light topic brackets is too ugly

![image](https://user-images.githubusercontent.com/8848263/53777450-619c6700-3f34-11e9-9142-a1fab4ebadf1.png)

![image](https://user-images.githubusercontent.com/8848263/53777474-7c6edb80-3f34-11e9-9289-69515655b601.png)

**Comment by UziTech** [comment]
https://github.com/vn-ki/bracket-colorizer#change-colors

**Comment by linjialiang** [comment]
thank you
