### ISSUE TITLE
Brackets inside $$ are not colored

### ISSUE THREAD

**Issue by BeastyBlacksmith** [vn-ki/bracket-colorizer#23]
Not sure if this is intentional or not, but `$ a(2) $` does not get colored.

**Comment by UziTech** [comment]
What grammar is that in?

It works for me in JavaScript 
![image](https://user-images.githubusercontent.com/97994/61057494-0e8f6080-a3bb-11e9-955c-a4c3b1bc4a77.png)

**Comment by BeastyBlacksmith** [comment]
thats LaTeX, so maybe it gets overridden

**Comment by UziTech** [comment]
Looks like the scope for that syntax is `string.other.math.tex`.

We filter out strings, regular expressions, and comments in [isRangeCommentedOrString(...)](https://github.com/vn-ki/bracket-colorizer/blob/master/lib/bracket-matcher.js#L107)

We could add an exception for that scope with LaTeX grammar.

@BeastyBlacksmith if you want to create a PR I would be happy to review it.
