### ISSUE TITLE
Color by nesting agnostic of bracket type

### ISSUE THREAD

**Issue by BeastyBlacksmith** [vn-ki/bracket-colorizer#25]
Currently `{[()]}` would display all braces in the same color.
Personally I would prefer to have the coloring indicate the nesting level irrespective of the type of bracket.

**Comment by UziTech** [comment]
There is an option for that

![image](https://user-images.githubusercontent.com/97994/60028510-0d450080-9665-11e9-869b-aa9b02be1b74.png)

**Comment by BeastyBlacksmith** [comment]
missed that ^^; very handy.
