### ISSUE TITLE
The package has no main.js file

### ISSUE THREAD

**Issue by abdelelrahman97** [vn-ki/bracket-colorizer#28]
![Cacccccccccpture](https://user-images.githubusercontent.com/60822166/80940717-e86efd00-8de0-11ea-8f2d-fd37d604bac7.PNG)

when i try to install it give me this eror

**Comment by UziTech** [comment]
Where are you trying to install this package? That doesn't look like Atom.

**Comment by abdelelrahman97** [comment]
in brackets
