### ISSUE TITLE
Colorization in comments.

### ISSUE THREAD

**Issue by oltodosel** [vn-ki/bracket-colorizer#3]
I think it is unnecessary.

**Comment by vn-ki** [comment]
I will look into it but I'm not sure whether I can fix it or not. The best way to go about would be to improve the regex in `bracket-matcher.js`.

https://github.com/vn-ki/bracket-colorizer/blob/d097a86a90514ca843070dcf2eb42cfca10f1673/lib/bracket-matcher.js#L17-L19
